# Generated by Django 4.2.1 on 2023-09-08 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0005_alter_studentgroup_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                (
                    "owner_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "topic_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic_name", models.CharField(max_length=50)),
                (
                    "course_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "list_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("list_name", models.CharField(max_length=50)),
                (
                    "topic_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.topic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_condition", models.TextField()),
                ("task_image", models.BinaryField(blank=True, null=True)),
                ("task_answer", models.CharField(max_length=50)),
                ("criteria", models.TextField()),
                (
                    "topic_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.topic"
                    ),
                ),
            ],
        ),
    ]
