# Generated by Django 4.2.1 on 2023-10-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="topic_uuid",
        ),
        migrations.AddField(
            model_name="task",
            name="list_uuid",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.tasklist",
            ),
            preserve_default=False,
        ),
    ]
