# Generated by Django 4.2.1 on 2023-10-11 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_task_format_task_max_ball"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="max_ball",
        ),
    ]
