# Generated by Django 4.2.1 on 2023-10-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_remove_task_max_ball"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_answer",
        ),
        migrations.AddField(
            model_name="task",
            name="max_ball",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
