# Generated by Django 4.2.1 on 2023-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_alter_tutor_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='password_hash',
            field=models.CharField(max_length=257),
        ),
    ]
