# Generated by Django 4.2.1 on 2023-09-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_reg', '0001_initial'),
        ('mainsite', '0004_alter_tutor_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='owner_uuid',
        ),
        migrations.RemoveField(
            model_name='studentgrouprelationship',
            name='group_uuid',
        ),
        migrations.RemoveField(
            model_name='studentgrouprelationship',
            name='student_uuid',
        ),
        migrations.RemoveField(
            model_name='studenttutorrelationship',
            name='student_uuid',
        ),
        migrations.RemoveField(
            model_name='studenttutorrelationship',
            name='tutor_uuid',
        ),
        migrations.AlterField(
            model_name='course',
            name='owner_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_and_reg.tutor'),
        ),
        migrations.AlterField(
            model_name='tasklistgrouprelationship',
            name='group_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_and_reg.studentgroup'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentGroup',
        ),
        migrations.DeleteModel(
            name='StudentGroupRelationship',
        ),
        migrations.DeleteModel(
            name='StudentTutorRelationship',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
