# Generated by Django 4.2.1 on 2023-09-06 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_reg', '0002_alter_tutor_email_alter_tutor_phone_number'),
        ('mainsite', '0005_remove_studentgroup_owner_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(default='http://moblen.ru/ref/6be587f4-ad80-45f1-a2be-9b16ef8dcd35', editable=False)),
                ('expires', models.DateTimeField(default=datetime.datetime(2023, 9, 6, 21, 12, 50, 908976, tzinfo=datetime.timezone.utc))),
                ('group_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_and_reg.studentgroup')),
                ('owner_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_and_reg.tutor')),
            ],
        ),
    ]
