# Generated by Django 4.2.1 on 2023-09-06 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_referrallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallink',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 21, 36, 13, 168227, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='url',
            field=models.URLField(default='http://moblen.ru/ref/ccec08ab-7e11-4f39-a6d2-cd45a3ad0d41', editable=False),
        ),
    ]
