# Generated by Django 4.2.1 on 2023-09-08 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_alter_referrallink_expires_alter_referrallink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallink',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 10, 25, 28, 896061, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='url',
            field=models.URLField(default='http://moblen.ru/ref/77d0d30f-37dd-4f5b-89ac-4fe769d63dbd', editable=False),
        ),
    ]
