# Generated by Django 4.2.1 on 2023-09-08 09:57

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0007_alter_referrallink_expires_alter_referrallink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referrallink",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 8, 11, 57, 36, 488738, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="url",
            field=models.URLField(
                default="http://None/ref/118ee57b-02f7-4097-9c32-a6ea4112b983",
                editable=False,
            ),
        ),
    ]
