<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-09-08 08:25
=======
# Generated by Django 4.2.1 on 2023-09-08 09:57
>>>>>>> 1522e1b433bdce4fb1f1116968c8217910bfe2a8

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('mainsite', '0007_alter_referrallink_expires_alter_referrallink_url'),
=======
    dependencies = [
        ("mainsite", "0007_alter_referrallink_expires_alter_referrallink_url"),
>>>>>>> 1522e1b433bdce4fb1f1116968c8217910bfe2a8
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='referrallink',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 10, 25, 28, 896061, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='url',
            field=models.URLField(default='http://moblen.ru/ref/77d0d30f-37dd-4f5b-89ac-4fe769d63dbd', editable=False),
=======
            model_name="referrallink",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 8, 11, 57, 36, 488738, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="url",
            field=models.URLField(
                default="http://None/ref/118ee57b-02f7-4097-9c32-a6ea4112b983",
                editable=False,
            ),
>>>>>>> 1522e1b433bdce4fb1f1116968c8217910bfe2a8
        ),
    ]
