# Generated by Django 4.2.1 on 2023-09-08 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0008_alter_referrallink_expires_alter_referrallink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referrallink",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 8, 11, 58, 14, 706444, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="url",
            field=models.URLField(
                default="http://None/ref/61963661-bbc1-4b4d-b3e0-b3ccedae71e6",
                editable=False,
            ),
        ),
    ]
