# Generated by Django 4.2.1 on 2023-09-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_alter_referrallink_expires_alter_referrallink_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralLink',
        ),
    ]
