# Generated by Django 4.2.1 on 2023-09-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("mainsite", "0010_delete_referrallink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="topic_uuid",
        ),
        migrations.RemoveField(
            model_name="tasklist",
            name="topic_uuid",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="course_uuid",
        ),
        migrations.AlterField(
            model_name="tasklistgrouprelationship",
            name="list_uuid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.tasklist"
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskList",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
