# Generated by Django 4.2.1 on 2023-09-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_studentgroup_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentgrouprelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentgrouprelationship',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentgrouprelationship',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentGroup',
        ),
        migrations.DeleteModel(
            name='StudentGroupRelationship',
        ),
    ]
