# Generated by Django 4.1.10 on 2023-09-25 19:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('customers', '0013_alter_student_email_alter_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('group_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=256, unique=True)),
                ('owner_uuid', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='customers.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TaskListGroupRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studentgroup')),
                ('list_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.tasklist')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroupRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studentgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.student')),
            ],
            options={
                'unique_together': {('student', 'group')},
            },
        ),
    ]
