# Generated by Django 4.2.1 on 2023-09-15 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("groups", "0004_delete_tasklistgrouprelationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskListGroupRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.studentgroup",
                    ),
                ),
                (
                    "list_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.tasklist",
                    ),
                ),
            ],
        ),
    ]
