# Generated by Django 4.1.10 on 2023-09-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_tasklistgrouprelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='url',
            field=models.TextField(max_length=200),
        ),
    ]
