# Generated by Django 4.2.1 on 2023-10-16 08:34

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
