# Generated by Django 4.2.1 on 2023-10-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('ST', 'student'), ('TT', 'tutor')], max_length=10, null=True),
        ),
    ]
