# Generated by Django 4.2.1 on 2023-09-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_and_reg", "0004_studentgroup_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="url",
            field=models.TextField(
                default="http://moblen.ru/ref/2d1a33ff-d9cb-4e80-acae-7cf244af0c52",
                unique=True,
            ),
        ),
    ]
