# Generated by Django 4.2.1 on 2023-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_student_password_hash_alter_student_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='url',
            field=models.TextField(default='http://moblen.ru/ref/f6750f2f-7d9c-4627-9606-9bac342d8a45'),
        ),
    ]
