# Generated by Django 4.2.1 on 2023-09-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_studentgroup_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='url',
            field=models.TextField(default='http://moblen.ru/ref/c331a3ac-4118-4613-bbe0-518da313f451'),
        ),
    ]
