# Generated by Django 4.2.1 on 2023-09-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_studentgroup_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='owner_uuid',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='customers.tutor'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='url',
            field=models.TextField(default='http://moblen.ru/ref/b00584ff-5907-4503-9d95-f9a59ffc771a'),
        ),
    ]
