# Generated by Django 4.2.1 on 2023-09-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_studentgroup_owner_uuid_alter_studentgroup_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrouprelationship',
            old_name='group_uuid',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='studentgrouprelationship',
            old_name='student_uuid',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='url',
            field=models.TextField(default='http://moblen.ru/ref/a86cacf1-ab43-4642-80da-4cdbda96ac2a'),
        ),
    ]
