# Generated by Django 4.2.1 on 2023-09-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_rename_group_uuid_studentgrouprelationship_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='url',
            field=models.TextField(default='http://moblen.ru/ref/de8c4185-308a-413b-8f88-199fed8f9498'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgrouprelationship',
            unique_together={('student', 'group')},
        ),
    ]
