# Generated by Django 4.2.1 on 2023-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_tutor_email_alter_tutor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
