# Generated by Django 4.2.1 on 2023-09-13 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0010_alter_studentgrouprelationship_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('group_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
                ('url', models.TextField(default='http://moblen.ru/ref/087d669a-4893-4aa8-ad61-94628fdc4234', unique=True)),
                ('owner_uuid', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='customers.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroupRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studentgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.student')),
            ],
            options={
                'unique_together': {('student', 'group')},
            },
        ),
    ]
