# Generated by Django 4.2.1 on 2023-09-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='url',
            field=models.TextField(default='http://moblen.ru/ref/40cb58ae-cda5-4a6c-9bab-7b3ea954579f', unique=True),
        ),
        migrations.CreateModel(
            name='TaskListGroupRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studentgroup')),
                ('list_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.tasklist')),
            ],
        ),
    ]
