# Generated by Django 4.2.1 on 2023-09-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_studentgroup_url_tasklistgrouprelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
