# Generated by Django 4.2.1 on 2023-09-15 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_alter_studentgroup_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskListGroupRelationship",
        ),
    ]
